#include <stdio.h>
#include <stdlib.h>
#include <time.h>

int main()
{
    time_t t; // Variable to store the current time
    // time_t: A data type defined in <time.h> for storing time values.
    // It is typically an integer type that represents the time in seconds
    // since the Unix epoch (January 1, 1970).

    // Seed the random number generator using the current time
    srand((unsigned)time(&t));
    // time(&t)->Gets the current time in seconds since the Unix epoch and stores it in the variable t. It also returns this value.
    // (unsigned)->Converts the time value to an unsigned integer type to match the parameter type expected by srand().
    // srand():Seeds the random number generator with the provided value. By using the current time, the seed value changes each time the program runs, ensuring that the sequence of random numbers generated by rand() is different on each execution.

    // Generate and print 5 random numbers
    for (int i = 0; i < 5; i++)
    {
        printf("%d\n", rand()); // Generate and print a random number
    }

    return 0; // Indicate successful execution
}
